-- ================================================================
-- 02_seed_data.sql - Datos semilla (regiones, categorías, productos)
-- NOTA: No existe tabla de ciudades. La validación ciudad → región
-- la realiza el LLM con conocimiento geográfico en el system prompt.
-- ================================================================

-- REGIONES (6 regiones de cobertura)
INSERT INTO public.regiones (nombre, slug) VALUES
  ('Antioquia', 'antioquia'),
  ('Atlantico', 'atlantico'),
  ('Bogota', 'bogota'),
  ('Eje Cafetero', 'eje-cafetero'),
  ('Norte de Santander', 'norte-de-santander'),
  ('Santander', 'santander')
ON CONFLICT (nombre) DO NOTHING;

-- CATEGORIAS
INSERT INTO public.categorias (nombre) VALUES
  ('Pollo'),
  ('Pollo Procesado'),
  ('Mariscos'),
  ('Pescado Procesado'),
  ('Carnes frias'),
  ('Pescado')
ON CONFLICT (nombre) DO NOTHING;

-- PRODUCTOS (55 productos del catálogo Friko/Antillana)
INSERT INTO public.productos (sku, marca, nombre, descripcion, categoria_id, region_id, gramos, unidades, pers_min, pers_max, metodos_preparacion, contenido_semantico, metadata) VALUES
  ('FRIK-002', 'FRIKO', 'Alitas picantes', 'Alitas marinadas picantes', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Antioquia'), 900, 12, 4, 6, '{"Horno","Airfryer"}', 'Producto Friko: Alitas picantes. Marca: FRIKO. Descripción: Alitas marinadas picantes. Categoría: Pollo. Región disponible: Antioquia. Gramaje: 900g. Rinde para 4 a 6 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-002", "marca": "FRIKO", "region": "Antioquia", "categoria": "Pollo", "pers_min": 4, "pers_max": 6, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('FRIK-003', 'FRIKO', 'Bombones BBQ', 'Pollo apanado precocido', (SELECT id FROM public.categorias WHERE nombre = 'Pollo Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Antioquia'), 500, 10, 2, 3, '{"Sarten","Horno"}', 'Producto Friko: Bombones BBQ. Marca: FRIKO. Descripción: Pollo apanado precocido. Categoría: Pollo Procesado. Región disponible: Antioquia. Gramaje: 500g. Rinde para 2 a 3 personas. Métodos de preparación: Sarten, Horno.', '{"sku": "FRIK-003", "marca": "FRIKO", "region": "Antioquia", "categoria": "Pollo Procesado", "pers_min": 2, "pers_max": 3, "metodos": ["Sarten", "Horno"]}'::jsonb),
  ('ANTI-001', 'ANTILLANA', 'Brochetas de langostino', 'Langostino en pincho', (SELECT id FROM public.categorias WHERE nombre = 'Mariscos'), (SELECT id FROM public.regiones WHERE nombre = 'Antioquia'), 600, 6, 4, 6, '{"Parrilla"}', 'Producto Friko: Brochetas de langostino. Marca: ANTILLANA. Descripción: Langostino en pincho. Categoría: Mariscos. Región disponible: Antioquia. Gramaje: 600g. Rinde para 4 a 6 personas. Métodos de preparación: Parrilla.', '{"sku": "ANTI-001", "marca": "ANTILLANA", "region": "Antioquia", "categoria": "Mariscos", "pers_min": 4, "pers_max": 6, "metodos": ["Parrilla"]}'::jsonb),
  ('ANTI-002', 'ANTILLANA', 'Camaron titi', 'Camaron precocido', (SELECT id FROM public.categorias WHERE nombre = 'Mariscos'), (SELECT id FROM public.regiones WHERE nombre = 'Antioquia'), 700, NULL, 4, 7, '{"Sarten","Salteado"}', 'Producto Friko: Camaron titi. Marca: ANTILLANA. Descripción: Camaron precocido. Categoría: Mariscos. Región disponible: Antioquia. Gramaje: 700g. Rinde para 4 a 7 personas. Métodos de preparación: Sarten, Salteado.', '{"sku": "ANTI-002", "marca": "ANTILLANA", "region": "Antioquia", "categoria": "Mariscos", "pers_min": 4, "pers_max": 7, "metodos": ["Sarten", "Salteado"]}'::jsonb),
  ('FRIK-005', 'FRIKO', 'Chuzos de contramuslo', 'Contramuslo marinado', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Antioquia'), 1900, 10, 9, 12, '{"Parrilla","Sarten"}', 'Producto Friko: Chuzos de contramuslo. Marca: FRIKO. Descripción: Contramuslo marinado. Categoría: Pollo. Región disponible: Antioquia. Gramaje: 1900g. Rinde para 9 a 12 personas. Métodos de preparación: Parrilla, Sarten.', '{"sku": "FRIK-005", "marca": "FRIKO", "region": "Antioquia", "categoria": "Pollo", "pers_min": 9, "pers_max": 12, "metodos": ["Parrilla", "Sarten"]}'::jsonb),
  ('ANTI-003', 'ANTILLANA', 'Dedos de merluza', 'Merluza apanada', (SELECT id FROM public.categorias WHERE nombre = 'Pescado Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Antioquia'), 800, 20, 5, 8, '{"Horno","Airfryer"}', 'Producto Friko: Dedos de merluza. Marca: ANTILLANA. Descripción: Merluza apanada. Categoría: Pescado Procesado. Región disponible: Antioquia. Gramaje: 800g. Rinde para 5 a 8 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "ANTI-003", "marca": "ANTILLANA", "region": "Antioquia", "categoria": "Pescado Procesado", "pers_min": 5, "pers_max": 8, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('FRIK-006', 'FRIKO', 'Filete de pechuga', 'Pechuga sin piel', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Antioquia'), 900, NULL, 4, 6, '{"Sarten","Plancha"}', 'Producto Friko: Filete de pechuga. Marca: FRIKO. Descripción: Pechuga sin piel. Categoría: Pollo. Región disponible: Antioquia. Gramaje: 900g. Rinde para 4 a 6 personas. Métodos de preparación: Sarten, Plancha.', '{"sku": "FRIK-006", "marca": "FRIKO", "region": "Antioquia", "categoria": "Pollo", "pers_min": 4, "pers_max": 6, "metodos": ["Sarten", "Plancha"]}'::jsonb),
  ('FRIK-007', 'FRIKO', 'Lomitos de pechuga', 'Lomitos congelados', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Antioquia'), 2000, NULL, 10, 13, '{"Sarten","Wok"}', 'Producto Friko: Lomitos de pechuga. Marca: FRIKO. Descripción: Lomitos congelados. Categoría: Pollo. Región disponible: Antioquia. Gramaje: 2000g. Rinde para 10 a 13 personas. Métodos de preparación: Sarten, Wok.', '{"sku": "FRIK-007", "marca": "FRIKO", "region": "Antioquia", "categoria": "Pollo", "pers_min": 10, "pers_max": 13, "metodos": ["Sarten", "Wok"]}'::jsonb),
  ('FRIK-009', 'FRIKO', 'Nuggets de pollo', 'Nuggets apanados', (SELECT id FROM public.categorias WHERE nombre = 'Pollo Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Antioquia'), 520, 24, 2, 3, '{"Horno","Airfryer"}', 'Producto Friko: Nuggets de pollo. Marca: FRIKO. Descripción: Nuggets apanados. Categoría: Pollo Procesado. Región disponible: Antioquia. Gramaje: 520g. Rinde para 2 a 3 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-009", "marca": "FRIKO", "region": "Antioquia", "categoria": "Pollo Procesado", "pers_min": 2, "pers_max": 3, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('FRIK-001', 'FRIKO', 'Alitas BBQ', 'Alitas marinadas BBQ', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 900, 12, 4, 6, '{"Horno","Airfryer"}', 'Producto Friko: Alitas BBQ. Marca: FRIKO. Descripción: Alitas marinadas BBQ. Categoría: Pollo. Región disponible: Atlantico. Gramaje: 900g. Rinde para 4 a 6 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-001", "marca": "FRIKO", "region": "Atlantico", "categoria": "Pollo", "pers_min": 4, "pers_max": 6, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('FRIK-002', 'FRIKO', 'Alitas picantes', 'Alitas marinadas picantes', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 900, 12, 4, 6, '{"Horno","Airfryer"}', 'Producto Friko: Alitas picantes. Marca: FRIKO. Descripción: Alitas marinadas picantes. Categoría: Pollo. Región disponible: Atlantico. Gramaje: 900g. Rinde para 4 a 6 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-002", "marca": "FRIKO", "region": "Atlantico", "categoria": "Pollo", "pers_min": 4, "pers_max": 6, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('ANTI-001', 'ANTILLANA', 'Brochetas de langostino', 'Langostino en pincho', (SELECT id FROM public.categorias WHERE nombre = 'Mariscos'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 600, 6, 4, 6, '{"Parrilla"}', 'Producto Friko: Brochetas de langostino. Marca: ANTILLANA. Descripción: Langostino en pincho. Categoría: Mariscos. Región disponible: Atlantico. Gramaje: 600g. Rinde para 4 a 6 personas. Métodos de preparación: Parrilla.', '{"sku": "ANTI-001", "marca": "ANTILLANA", "region": "Atlantico", "categoria": "Mariscos", "pers_min": 4, "pers_max": 6, "metodos": ["Parrilla"]}'::jsonb),
  ('ANTI-002', 'ANTILLANA', 'Camaron titi', 'Camaron precocido', (SELECT id FROM public.categorias WHERE nombre = 'Mariscos'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 700, NULL, 4, 7, '{"Sarten","Salteado"}', 'Producto Friko: Camaron titi. Marca: ANTILLANA. Descripción: Camaron precocido. Categoría: Mariscos. Región disponible: Atlantico. Gramaje: 700g. Rinde para 4 a 7 personas. Métodos de preparación: Sarten, Salteado.', '{"sku": "ANTI-002", "marca": "ANTILLANA", "region": "Atlantico", "categoria": "Mariscos", "pers_min": 4, "pers_max": 7, "metodos": ["Sarten", "Salteado"]}'::jsonb),
  ('FRIK-004', 'FRIKO', 'Chorizo de pollo', 'Chorizo tipo parrillero', (SELECT id FROM public.categorias WHERE nombre = 'Carnes frias'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 2000, 20, 10, 13, '{"Parrilla","Sarten"}', 'Producto Friko: Chorizo de pollo. Marca: FRIKO. Descripción: Chorizo tipo parrillero. Categoría: Carnes frias. Región disponible: Atlantico. Gramaje: 2000g. Rinde para 10 a 13 personas. Métodos de preparación: Parrilla, Sarten.', '{"sku": "FRIK-004", "marca": "FRIKO", "region": "Atlantico", "categoria": "Carnes frias", "pers_min": 10, "pers_max": 13, "metodos": ["Parrilla", "Sarten"]}'::jsonb),
  ('FRIK-005', 'FRIKO', 'Chuzos de contramuslo', 'Contramuslo marinado', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 1900, 10, 9, 12, '{"Parrilla","Sarten"}', 'Producto Friko: Chuzos de contramuslo. Marca: FRIKO. Descripción: Contramuslo marinado. Categoría: Pollo. Región disponible: Atlantico. Gramaje: 1900g. Rinde para 9 a 12 personas. Métodos de preparación: Parrilla, Sarten.', '{"sku": "FRIK-005", "marca": "FRIKO", "region": "Atlantico", "categoria": "Pollo", "pers_min": 9, "pers_max": 12, "metodos": ["Parrilla", "Sarten"]}'::jsonb),
  ('ANTI-003', 'ANTILLANA', 'Dedos de merluza', 'Merluza apanada', (SELECT id FROM public.categorias WHERE nombre = 'Pescado Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 800, 20, 5, 8, '{"Horno","Airfryer"}', 'Producto Friko: Dedos de merluza. Marca: ANTILLANA. Descripción: Merluza apanada. Categoría: Pescado Procesado. Región disponible: Atlantico. Gramaje: 800g. Rinde para 5 a 8 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "ANTI-003", "marca": "ANTILLANA", "region": "Atlantico", "categoria": "Pescado Procesado", "pers_min": 5, "pers_max": 8, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('ANTI-004', 'ANTILLANA', 'Filete de salmon premium', 'Salmon importado', (SELECT id FROM public.categorias WHERE nombre = 'Pescado'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 450, NULL, 3, 4, '{"Plancha","Horno"}', 'Producto Friko: Filete de salmon premium. Marca: ANTILLANA. Descripción: Salmon importado. Categoría: Pescado. Región disponible: Atlantico. Gramaje: 450g. Rinde para 3 a 4 personas. Métodos de preparación: Plancha, Horno.', '{"sku": "ANTI-004", "marca": "ANTILLANA", "region": "Atlantico", "categoria": "Pescado", "pers_min": 3, "pers_max": 4, "metodos": ["Plancha", "Horno"]}'::jsonb),
  ('ANTI-005', 'ANTILLANA', 'Hamburguesa de salmon', 'Hamburguesa gourmet', (SELECT id FROM public.categorias WHERE nombre = 'Pescado Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 454, 6, 3, 4, '{"Sarten","Parrilla"}', 'Producto Friko: Hamburguesa de salmon. Marca: ANTILLANA. Descripción: Hamburguesa gourmet. Categoría: Pescado Procesado. Región disponible: Atlantico. Gramaje: 454g. Rinde para 3 a 4 personas. Métodos de preparación: Sarten, Parrilla.', '{"sku": "ANTI-005", "marca": "ANTILLANA", "region": "Atlantico", "categoria": "Pescado Procesado", "pers_min": 3, "pers_max": 4, "metodos": ["Sarten", "Parrilla"]}'::jsonb),
  ('FRIK-007', 'FRIKO', 'Lomitos de pechuga', 'Lomitos congelados', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 2000, NULL, 10, 13, '{"Sarten","Wok"}', 'Producto Friko: Lomitos de pechuga. Marca: FRIKO. Descripción: Lomitos congelados. Categoría: Pollo. Región disponible: Atlantico. Gramaje: 2000g. Rinde para 10 a 13 personas. Métodos de preparación: Sarten, Wok.', '{"sku": "FRIK-007", "marca": "FRIKO", "region": "Atlantico", "categoria": "Pollo", "pers_min": 10, "pers_max": 13, "metodos": ["Sarten", "Wok"]}'::jsonb),
  ('FRIK-009', 'FRIKO', 'Nuggets de pollo', 'Nuggets apanados', (SELECT id FROM public.categorias WHERE nombre = 'Pollo Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Atlantico'), 520, 24, 2, 3, '{"Horno","Airfryer"}', 'Producto Friko: Nuggets de pollo. Marca: FRIKO. Descripción: Nuggets apanados. Categoría: Pollo Procesado. Región disponible: Atlantico. Gramaje: 520g. Rinde para 2 a 3 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-009", "marca": "FRIKO", "region": "Atlantico", "categoria": "Pollo Procesado", "pers_min": 2, "pers_max": 3, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('FRIK-003', 'FRIKO', 'Bombones BBQ', 'Pollo apanado precocido', (SELECT id FROM public.categorias WHERE nombre = 'Pollo Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Bogota'), 500, 10, 2, 3, '{"Sarten","Horno"}', 'Producto Friko: Bombones BBQ. Marca: FRIKO. Descripción: Pollo apanado precocido. Categoría: Pollo Procesado. Región disponible: Bogota. Gramaje: 500g. Rinde para 2 a 3 personas. Métodos de preparación: Sarten, Horno.', '{"sku": "FRIK-003", "marca": "FRIKO", "region": "Bogota", "categoria": "Pollo Procesado", "pers_min": 2, "pers_max": 3, "metodos": ["Sarten", "Horno"]}'::jsonb),
  ('FRIK-004', 'FRIKO', 'Chorizo de pollo', 'Chorizo tipo parrillero', (SELECT id FROM public.categorias WHERE nombre = 'Carnes frias'), (SELECT id FROM public.regiones WHERE nombre = 'Bogota'), 2000, 20, 10, 13, '{"Parrilla","Sarten"}', 'Producto Friko: Chorizo de pollo. Marca: FRIKO. Descripción: Chorizo tipo parrillero. Categoría: Carnes frias. Región disponible: Bogota. Gramaje: 2000g. Rinde para 10 a 13 personas. Métodos de preparación: Parrilla, Sarten.', '{"sku": "FRIK-004", "marca": "FRIKO", "region": "Bogota", "categoria": "Carnes frias", "pers_min": 10, "pers_max": 13, "metodos": ["Parrilla", "Sarten"]}'::jsonb),
  ('FRIK-005', 'FRIKO', 'Chuzos de contramuslo', 'Contramuslo marinado', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Bogota'), 1900, 10, 9, 12, '{"Parrilla","Sarten"}', 'Producto Friko: Chuzos de contramuslo. Marca: FRIKO. Descripción: Contramuslo marinado. Categoría: Pollo. Región disponible: Bogota. Gramaje: 1900g. Rinde para 9 a 12 personas. Métodos de preparación: Parrilla, Sarten.', '{"sku": "FRIK-005", "marca": "FRIKO", "region": "Bogota", "categoria": "Pollo", "pers_min": 9, "pers_max": 12, "metodos": ["Parrilla", "Sarten"]}'::jsonb),
  ('FRIK-006', 'FRIKO', 'Filete de pechuga', 'Pechuga sin piel', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Bogota'), 900, NULL, 4, 6, '{"Sarten","Plancha"}', 'Producto Friko: Filete de pechuga. Marca: FRIKO. Descripción: Pechuga sin piel. Categoría: Pollo. Región disponible: Bogota. Gramaje: 900g. Rinde para 4 a 6 personas. Métodos de preparación: Sarten, Plancha.', '{"sku": "FRIK-006", "marca": "FRIKO", "region": "Bogota", "categoria": "Pollo", "pers_min": 4, "pers_max": 6, "metodos": ["Sarten", "Plancha"]}'::jsonb),
  ('ANTI-004', 'ANTILLANA', 'Filete de salmon premium', 'Salmon importado', (SELECT id FROM public.categorias WHERE nombre = 'Pescado'), (SELECT id FROM public.regiones WHERE nombre = 'Bogota'), 450, NULL, 3, 4, '{"Plancha","Horno"}', 'Producto Friko: Filete de salmon premium. Marca: ANTILLANA. Descripción: Salmon importado. Categoría: Pescado. Región disponible: Bogota. Gramaje: 450g. Rinde para 3 a 4 personas. Métodos de preparación: Plancha, Horno.', '{"sku": "ANTI-004", "marca": "ANTILLANA", "region": "Bogota", "categoria": "Pescado", "pers_min": 3, "pers_max": 4, "metodos": ["Plancha", "Horno"]}'::jsonb),
  ('FRIK-007', 'FRIKO', 'Lomitos de pechuga', 'Lomitos congelados', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Bogota'), 2000, NULL, 10, 13, '{"Sarten","Wok"}', 'Producto Friko: Lomitos de pechuga. Marca: FRIKO. Descripción: Lomitos congelados. Categoría: Pollo. Región disponible: Bogota. Gramaje: 2000g. Rinde para 10 a 13 personas. Métodos de preparación: Sarten, Wok.', '{"sku": "FRIK-007", "marca": "FRIKO", "region": "Bogota", "categoria": "Pollo", "pers_min": 10, "pers_max": 13, "metodos": ["Sarten", "Wok"]}'::jsonb),
  ('ANTI-006', 'ANTILLANA', 'Medallones de pescado', 'Pescado blanco porcionado', (SELECT id FROM public.categorias WHERE nombre = 'Pescado'), (SELECT id FROM public.regiones WHERE nombre = 'Bogota'), 1200, 12, 8, 12, '{"Horno","Sarten"}', 'Producto Friko: Medallones de pescado. Marca: ANTILLANA. Descripción: Pescado blanco porcionado. Categoría: Pescado. Región disponible: Bogota. Gramaje: 1200g. Rinde para 8 a 12 personas. Métodos de preparación: Horno, Sarten.', '{"sku": "ANTI-006", "marca": "ANTILLANA", "region": "Bogota", "categoria": "Pescado", "pers_min": 8, "pers_max": 12, "metodos": ["Horno", "Sarten"]}'::jsonb),
  ('FRIK-008', 'FRIKO', 'Mini chuzos', 'Contramuslo marinado pequeno', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Bogota'), 540, 6, 2, 3, '{"Sarten","Airfryer"}', 'Producto Friko: Mini chuzos. Marca: FRIKO. Descripción: Contramuslo marinado pequeno. Categoría: Pollo. Región disponible: Bogota. Gramaje: 540g. Rinde para 2 a 3 personas. Métodos de preparación: Sarten, Airfryer.', '{"sku": "FRIK-008", "marca": "FRIKO", "region": "Bogota", "categoria": "Pollo", "pers_min": 2, "pers_max": 3, "metodos": ["Sarten", "Airfryer"]}'::jsonb),
  ('FRIK-009', 'FRIKO', 'Nuggets de pollo', 'Nuggets apanados', (SELECT id FROM public.categorias WHERE nombre = 'Pollo Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Bogota'), 520, 24, 2, 3, '{"Horno","Airfryer"}', 'Producto Friko: Nuggets de pollo. Marca: FRIKO. Descripción: Nuggets apanados. Categoría: Pollo Procesado. Región disponible: Bogota. Gramaje: 520g. Rinde para 2 a 3 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-009", "marca": "FRIKO", "region": "Bogota", "categoria": "Pollo Procesado", "pers_min": 2, "pers_max": 3, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('FRIK-002', 'FRIKO', 'Alitas picantes', 'Alitas marinadas picantes', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Eje Cafetero'), 900, 12, 4, 6, '{"Horno","Airfryer"}', 'Producto Friko: Alitas picantes. Marca: FRIKO. Descripción: Alitas marinadas picantes. Categoría: Pollo. Región disponible: Eje Cafetero. Gramaje: 900g. Rinde para 4 a 6 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-002", "marca": "FRIKO", "region": "Eje Cafetero", "categoria": "Pollo", "pers_min": 4, "pers_max": 6, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('FRIK-003', 'FRIKO', 'Bombones BBQ', 'Pollo apanado precocido', (SELECT id FROM public.categorias WHERE nombre = 'Pollo Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Eje Cafetero'), 500, 10, 2, 3, '{"Sarten","Horno"}', 'Producto Friko: Bombones BBQ. Marca: FRIKO. Descripción: Pollo apanado precocido. Categoría: Pollo Procesado. Región disponible: Eje Cafetero. Gramaje: 500g. Rinde para 2 a 3 personas. Métodos de preparación: Sarten, Horno.', '{"sku": "FRIK-003", "marca": "FRIKO", "region": "Eje Cafetero", "categoria": "Pollo Procesado", "pers_min": 2, "pers_max": 3, "metodos": ["Sarten", "Horno"]}'::jsonb),
  ('ANTI-001', 'ANTILLANA', 'Brochetas de langostino', 'Langostino en pincho', (SELECT id FROM public.categorias WHERE nombre = 'Mariscos'), (SELECT id FROM public.regiones WHERE nombre = 'Eje Cafetero'), 600, 6, 4, 6, '{"Parrilla"}', 'Producto Friko: Brochetas de langostino. Marca: ANTILLANA. Descripción: Langostino en pincho. Categoría: Mariscos. Región disponible: Eje Cafetero. Gramaje: 600g. Rinde para 4 a 6 personas. Métodos de preparación: Parrilla.', '{"sku": "ANTI-001", "marca": "ANTILLANA", "region": "Eje Cafetero", "categoria": "Mariscos", "pers_min": 4, "pers_max": 6, "metodos": ["Parrilla"]}'::jsonb),
  ('FRIK-004', 'FRIKO', 'Chorizo de pollo', 'Chorizo tipo parrillero', (SELECT id FROM public.categorias WHERE nombre = 'Carnes frias'), (SELECT id FROM public.regiones WHERE nombre = 'Eje Cafetero'), 2000, 20, 10, 13, '{"Parrilla","Sarten"}', 'Producto Friko: Chorizo de pollo. Marca: FRIKO. Descripción: Chorizo tipo parrillero. Categoría: Carnes frias. Región disponible: Eje Cafetero. Gramaje: 2000g. Rinde para 10 a 13 personas. Métodos de preparación: Parrilla, Sarten.', '{"sku": "FRIK-004", "marca": "FRIKO", "region": "Eje Cafetero", "categoria": "Carnes frias", "pers_min": 10, "pers_max": 13, "metodos": ["Parrilla", "Sarten"]}'::jsonb),
  ('FRIK-005', 'FRIKO', 'Chuzos de contramuslo', 'Contramuslo marinado', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Eje Cafetero'), 1900, 10, 9, 12, '{"Parrilla","Sarten"}', 'Producto Friko: Chuzos de contramuslo. Marca: FRIKO. Descripción: Contramuslo marinado. Categoría: Pollo. Región disponible: Eje Cafetero. Gramaje: 1900g. Rinde para 9 a 12 personas. Métodos de preparación: Parrilla, Sarten.', '{"sku": "FRIK-005", "marca": "FRIKO", "region": "Eje Cafetero", "categoria": "Pollo", "pers_min": 9, "pers_max": 12, "metodos": ["Parrilla", "Sarten"]}'::jsonb),
  ('ANTI-003', 'ANTILLANA', 'Dedos de merluza', 'Merluza apanada', (SELECT id FROM public.categorias WHERE nombre = 'Pescado Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Eje Cafetero'), 800, 20, 5, 8, '{"Horno","Airfryer"}', 'Producto Friko: Dedos de merluza. Marca: ANTILLANA. Descripción: Merluza apanada. Categoría: Pescado Procesado. Región disponible: Eje Cafetero. Gramaje: 800g. Rinde para 5 a 8 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "ANTI-003", "marca": "ANTILLANA", "region": "Eje Cafetero", "categoria": "Pescado Procesado", "pers_min": 5, "pers_max": 8, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('ANTI-004', 'ANTILLANA', 'Filete de salmon premium', 'Salmon importado', (SELECT id FROM public.categorias WHERE nombre = 'Pescado'), (SELECT id FROM public.regiones WHERE nombre = 'Eje Cafetero'), 450, NULL, 3, 4, '{"Plancha","Horno"}', 'Producto Friko: Filete de salmon premium. Marca: ANTILLANA. Descripción: Salmon importado. Categoría: Pescado. Región disponible: Eje Cafetero. Gramaje: 450g. Rinde para 3 a 4 personas. Métodos de preparación: Plancha, Horno.', '{"sku": "ANTI-004", "marca": "ANTILLANA", "region": "Eje Cafetero", "categoria": "Pescado", "pers_min": 3, "pers_max": 4, "metodos": ["Plancha", "Horno"]}'::jsonb),
  ('ANTI-005', 'ANTILLANA', 'Hamburguesa de salmon', 'Hamburguesa gourmet', (SELECT id FROM public.categorias WHERE nombre = 'Pescado Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Eje Cafetero'), 454, 6, 3, 4, '{"Sarten","Parrilla"}', 'Producto Friko: Hamburguesa de salmon. Marca: ANTILLANA. Descripción: Hamburguesa gourmet. Categoría: Pescado Procesado. Región disponible: Eje Cafetero. Gramaje: 454g. Rinde para 3 a 4 personas. Métodos de preparación: Sarten, Parrilla.', '{"sku": "ANTI-005", "marca": "ANTILLANA", "region": "Eje Cafetero", "categoria": "Pescado Procesado", "pers_min": 3, "pers_max": 4, "metodos": ["Sarten", "Parrilla"]}'::jsonb),
  ('FRIK-008', 'FRIKO', 'Mini chuzos', 'Contramuslo marinado pequeno', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Eje Cafetero'), 540, 6, 2, 3, '{"Sarten","Airfryer"}', 'Producto Friko: Mini chuzos. Marca: FRIKO. Descripción: Contramuslo marinado pequeno. Categoría: Pollo. Región disponible: Eje Cafetero. Gramaje: 540g. Rinde para 2 a 3 personas. Métodos de preparación: Sarten, Airfryer.', '{"sku": "FRIK-008", "marca": "FRIKO", "region": "Eje Cafetero", "categoria": "Pollo", "pers_min": 2, "pers_max": 3, "metodos": ["Sarten", "Airfryer"]}'::jsonb),
  ('FRIK-009', 'FRIKO', 'Nuggets de pollo', 'Nuggets apanados', (SELECT id FROM public.categorias WHERE nombre = 'Pollo Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Eje Cafetero'), 520, 24, 2, 3, '{"Horno","Airfryer"}', 'Producto Friko: Nuggets de pollo. Marca: FRIKO. Descripción: Nuggets apanados. Categoría: Pollo Procesado. Región disponible: Eje Cafetero. Gramaje: 520g. Rinde para 2 a 3 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-009", "marca": "FRIKO", "region": "Eje Cafetero", "categoria": "Pollo Procesado", "pers_min": 2, "pers_max": 3, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('FRIK-001', 'FRIKO', 'Alitas BBQ', 'Alitas marinadas BBQ', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Norte de Santander'), 900, 12, 4, 6, '{"Horno","Airfryer"}', 'Producto Friko: Alitas BBQ. Marca: FRIKO. Descripción: Alitas marinadas BBQ. Categoría: Pollo. Región disponible: Norte de Santander. Gramaje: 900g. Rinde para 4 a 6 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-001", "marca": "FRIKO", "region": "Norte de Santander", "categoria": "Pollo", "pers_min": 4, "pers_max": 6, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('ANTI-001', 'ANTILLANA', 'Brochetas de langostino', 'Langostino en pincho', (SELECT id FROM public.categorias WHERE nombre = 'Mariscos'), (SELECT id FROM public.regiones WHERE nombre = 'Norte de Santander'), 600, 6, 4, 6, '{"Parrilla"}', 'Producto Friko: Brochetas de langostino. Marca: ANTILLANA. Descripción: Langostino en pincho. Categoría: Mariscos. Región disponible: Norte de Santander. Gramaje: 600g. Rinde para 4 a 6 personas. Métodos de preparación: Parrilla.', '{"sku": "ANTI-001", "marca": "ANTILLANA", "region": "Norte de Santander", "categoria": "Mariscos", "pers_min": 4, "pers_max": 6, "metodos": ["Parrilla"]}'::jsonb),
  ('ANTI-002', 'ANTILLANA', 'Camaron titi', 'Camaron precocido', (SELECT id FROM public.categorias WHERE nombre = 'Mariscos'), (SELECT id FROM public.regiones WHERE nombre = 'Norte de Santander'), 700, NULL, 4, 7, '{"Sarten","Salteado"}', 'Producto Friko: Camaron titi. Marca: ANTILLANA. Descripción: Camaron precocido. Categoría: Mariscos. Región disponible: Norte de Santander. Gramaje: 700g. Rinde para 4 a 7 personas. Métodos de preparación: Sarten, Salteado.', '{"sku": "ANTI-002", "marca": "ANTILLANA", "region": "Norte de Santander", "categoria": "Mariscos", "pers_min": 4, "pers_max": 7, "metodos": ["Sarten", "Salteado"]}'::jsonb),
  ('FRIK-004', 'FRIKO', 'Chorizo de pollo', 'Chorizo tipo parrillero', (SELECT id FROM public.categorias WHERE nombre = 'Carnes frias'), (SELECT id FROM public.regiones WHERE nombre = 'Norte de Santander'), 2000, 20, 10, 13, '{"Parrilla","Sarten"}', 'Producto Friko: Chorizo de pollo. Marca: FRIKO. Descripción: Chorizo tipo parrillero. Categoría: Carnes frias. Región disponible: Norte de Santander. Gramaje: 2000g. Rinde para 10 a 13 personas. Métodos de preparación: Parrilla, Sarten.', '{"sku": "FRIK-004", "marca": "FRIKO", "region": "Norte de Santander", "categoria": "Carnes frias", "pers_min": 10, "pers_max": 13, "metodos": ["Parrilla", "Sarten"]}'::jsonb),
  ('ANTI-003', 'ANTILLANA', 'Dedos de merluza', 'Merluza apanada', (SELECT id FROM public.categorias WHERE nombre = 'Pescado Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Norte de Santander'), 800, 20, 5, 8, '{"Horno","Airfryer"}', 'Producto Friko: Dedos de merluza. Marca: ANTILLANA. Descripción: Merluza apanada. Categoría: Pescado Procesado. Región disponible: Norte de Santander. Gramaje: 800g. Rinde para 5 a 8 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "ANTI-003", "marca": "ANTILLANA", "region": "Norte de Santander", "categoria": "Pescado Procesado", "pers_min": 5, "pers_max": 8, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('FRIK-006', 'FRIKO', 'Filete de pechuga', 'Pechuga sin piel', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Norte de Santander'), 900, NULL, 4, 6, '{"Sarten","Plancha"}', 'Producto Friko: Filete de pechuga. Marca: FRIKO. Descripción: Pechuga sin piel. Categoría: Pollo. Región disponible: Norte de Santander. Gramaje: 900g. Rinde para 4 a 6 personas. Métodos de preparación: Sarten, Plancha.', '{"sku": "FRIK-006", "marca": "FRIKO", "region": "Norte de Santander", "categoria": "Pollo", "pers_min": 4, "pers_max": 6, "metodos": ["Sarten", "Plancha"]}'::jsonb),
  ('ANTI-005', 'ANTILLANA', 'Hamburguesa de salmon', 'Hamburguesa gourmet', (SELECT id FROM public.categorias WHERE nombre = 'Pescado Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Norte de Santander'), 454, 6, 3, 4, '{"Sarten","Parrilla"}', 'Producto Friko: Hamburguesa de salmon. Marca: ANTILLANA. Descripción: Hamburguesa gourmet. Categoría: Pescado Procesado. Región disponible: Norte de Santander. Gramaje: 454g. Rinde para 3 a 4 personas. Métodos de preparación: Sarten, Parrilla.', '{"sku": "ANTI-005", "marca": "ANTILLANA", "region": "Norte de Santander", "categoria": "Pescado Procesado", "pers_min": 3, "pers_max": 4, "metodos": ["Sarten", "Parrilla"]}'::jsonb),
  ('FRIK-007', 'FRIKO', 'Lomitos de pechuga', 'Lomitos congelados', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Norte de Santander'), 2000, NULL, 10, 13, '{"Sarten","Wok"}', 'Producto Friko: Lomitos de pechuga. Marca: FRIKO. Descripción: Lomitos congelados. Categoría: Pollo. Región disponible: Norte de Santander. Gramaje: 2000g. Rinde para 10 a 13 personas. Métodos de preparación: Sarten, Wok.', '{"sku": "FRIK-007", "marca": "FRIKO", "region": "Norte de Santander", "categoria": "Pollo", "pers_min": 10, "pers_max": 13, "metodos": ["Sarten", "Wok"]}'::jsonb),
  ('ANTI-006', 'ANTILLANA', 'Medallones de pescado', 'Pescado blanco porcionado', (SELECT id FROM public.categorias WHERE nombre = 'Pescado'), (SELECT id FROM public.regiones WHERE nombre = 'Norte de Santander'), 1200, 12, 8, 12, '{"Horno","Sarten"}', 'Producto Friko: Medallones de pescado. Marca: ANTILLANA. Descripción: Pescado blanco porcionado. Categoría: Pescado. Región disponible: Norte de Santander. Gramaje: 1200g. Rinde para 8 a 12 personas. Métodos de preparación: Horno, Sarten.', '{"sku": "ANTI-006", "marca": "ANTILLANA", "region": "Norte de Santander", "categoria": "Pescado", "pers_min": 8, "pers_max": 12, "metodos": ["Horno", "Sarten"]}'::jsonb),
  ('FRIK-001', 'FRIKO', 'Alitas BBQ', 'Alitas marinadas BBQ', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Santander'), 900, 12, 4, 6, '{"Horno","Airfryer"}', 'Producto Friko: Alitas BBQ. Marca: FRIKO. Descripción: Alitas marinadas BBQ. Categoría: Pollo. Región disponible: Santander. Gramaje: 900g. Rinde para 4 a 6 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-001", "marca": "FRIKO", "region": "Santander", "categoria": "Pollo", "pers_min": 4, "pers_max": 6, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('ANTI-001', 'ANTILLANA', 'Brochetas de langostino', 'Langostino en pincho', (SELECT id FROM public.categorias WHERE nombre = 'Mariscos'), (SELECT id FROM public.regiones WHERE nombre = 'Santander'), 600, 6, 4, 6, '{"Parrilla"}', 'Producto Friko: Brochetas de langostino. Marca: ANTILLANA. Descripción: Langostino en pincho. Categoría: Mariscos. Región disponible: Santander. Gramaje: 600g. Rinde para 4 a 6 personas. Métodos de preparación: Parrilla.', '{"sku": "ANTI-001", "marca": "ANTILLANA", "region": "Santander", "categoria": "Mariscos", "pers_min": 4, "pers_max": 6, "metodos": ["Parrilla"]}'::jsonb),
  ('ANTI-002', 'ANTILLANA', 'Camaron titi', 'Camaron precocido', (SELECT id FROM public.categorias WHERE nombre = 'Mariscos'), (SELECT id FROM public.regiones WHERE nombre = 'Santander'), 700, NULL, 4, 7, '{"Sarten","Salteado"}', 'Producto Friko: Camaron titi. Marca: ANTILLANA. Descripción: Camaron precocido. Categoría: Mariscos. Región disponible: Santander. Gramaje: 700g. Rinde para 4 a 7 personas. Métodos de preparación: Sarten, Salteado.', '{"sku": "ANTI-002", "marca": "ANTILLANA", "region": "Santander", "categoria": "Mariscos", "pers_min": 4, "pers_max": 7, "metodos": ["Sarten", "Salteado"]}'::jsonb),
  ('ANTI-003', 'ANTILLANA', 'Dedos de merluza', 'Merluza apanada', (SELECT id FROM public.categorias WHERE nombre = 'Pescado Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Santander'), 800, 20, 5, 8, '{"Horno","Airfryer"}', 'Producto Friko: Dedos de merluza. Marca: ANTILLANA. Descripción: Merluza apanada. Categoría: Pescado Procesado. Región disponible: Santander. Gramaje: 800g. Rinde para 5 a 8 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "ANTI-003", "marca": "ANTILLANA", "region": "Santander", "categoria": "Pescado Procesado", "pers_min": 5, "pers_max": 8, "metodos": ["Horno", "Airfryer"]}'::jsonb),
  ('ANTI-005', 'ANTILLANA', 'Hamburguesa de salmon', 'Hamburguesa gourmet', (SELECT id FROM public.categorias WHERE nombre = 'Pescado Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Santander'), 454, 6, 3, 4, '{"Sarten","Parrilla"}', 'Producto Friko: Hamburguesa de salmon. Marca: ANTILLANA. Descripción: Hamburguesa gourmet. Categoría: Pescado Procesado. Región disponible: Santander. Gramaje: 454g. Rinde para 3 a 4 personas. Métodos de preparación: Sarten, Parrilla.', '{"sku": "ANTI-005", "marca": "ANTILLANA", "region": "Santander", "categoria": "Pescado Procesado", "pers_min": 3, "pers_max": 4, "metodos": ["Sarten", "Parrilla"]}'::jsonb),
  ('FRIK-008', 'FRIKO', 'Mini chuzos', 'Contramuslo marinado pequeno', (SELECT id FROM public.categorias WHERE nombre = 'Pollo'), (SELECT id FROM public.regiones WHERE nombre = 'Santander'), 540, 6, 2, 3, '{"Sarten","Airfryer"}', 'Producto Friko: Mini chuzos. Marca: FRIKO. Descripción: Contramuslo marinado pequeno. Categoría: Pollo. Región disponible: Santander. Gramaje: 540g. Rinde para 2 a 3 personas. Métodos de preparación: Sarten, Airfryer.', '{"sku": "FRIK-008", "marca": "FRIKO", "region": "Santander", "categoria": "Pollo", "pers_min": 2, "pers_max": 3, "metodos": ["Sarten", "Airfryer"]}'::jsonb),
  ('FRIK-009', 'FRIKO', 'Nuggets de pollo', 'Nuggets apanados', (SELECT id FROM public.categorias WHERE nombre = 'Pollo Procesado'), (SELECT id FROM public.regiones WHERE nombre = 'Santander'), 520, 24, 2, 3, '{"Horno","Airfryer"}', 'Producto Friko: Nuggets de pollo. Marca: FRIKO. Descripción: Nuggets apanados. Categoría: Pollo Procesado. Región disponible: Santander. Gramaje: 520g. Rinde para 2 a 3 personas. Métodos de preparación: Horno, Airfryer.', '{"sku": "FRIK-009", "marca": "FRIKO", "region": "Santander", "categoria": "Pollo Procesado", "pers_min": 2, "pers_max": 3, "metodos": ["Horno", "Airfryer"]}'::jsonb)
ON CONFLICT (sku, region_id) DO NOTHING;
