-- ================================================================
-- 05_seed_producto_receta.sql  (v2 — join por titulo, no por id)
-- La versión anterior fallaba silenciosamente porque asumía que
-- r.id == posición en el JSON. bigserial no lo garantiza.
-- Esta versión busca cada receta por su titulo exacto.
-- Relevancia: 1=pasos  2=ingrediente  3=título/oficial
-- ================================================================

INSERT INTO public.producto_receta (producto_id, receta_id, relevancia)
SELECT p.id, r.id, matches.relevancia
FROM (VALUES
  ('FRIK-001', 'Alitas BBQ Friko  con papas rellenas', 3),
  ('FRIK-001', 'Papas más Crocantes Con Alitas BBQ', 3),
  ('FRIK-002', 'Top 3 alitas  más picantes', 2),
  ('FRIK-003', 'Alitas flameadasde Friko', 2),
  ('FRIK-003', 'Bombones BBQ', 3),
  ('FRIK-003', 'Bombones de pollo con salsa de yogurt', 3),
  ('FRIK-003', 'Bombones de polloBBQ con picante', 3),
  ('FRIK-003', 'Los bombones de pollo más rápidos y prácticos', 3),
  ('FRIK-003', 'Papas más Crocantes Con Alitas BBQ', 2),
  ('FRIK-003', 'Súper picada navideña', 2),
  ('FRIK-005', 'Arroz mixto  de pollo', 2),
  ('FRIK-005', 'Asado ligeroFriko', 2),
  ('FRIK-005', 'Asar pollo en sanduchera', 2),
  ('FRIK-005', 'Bowl de coliflor y  Pollo Friko', 2),
  ('FRIK-005', 'Burrito mexicanocon pollo BBQ', 2),
  ('FRIK-005', 'Chuzo Friko desgranado', 2),
  ('FRIK-005', 'Chuzos con mazorcas  y mantequilla saborizada', 2),
  ('FRIK-005', 'Contramuslosal horno', 3),
  ('FRIK-005', 'Contramuslos con papas al romero y ajo', 3),
  ('FRIK-005', 'Contramuslos contomates rostizados picosos', 3),
  ('FRIK-005', 'Cordon Blueal estilo Friko', 2),
  ('FRIK-005', 'Ensaladadecembrina', 2),
  ('FRIK-005', 'Estofado de  pollo y maíz', 2),
  ('FRIK-005', 'Filetes de contramuslos crocantescon risotto de tomates', 3),
  ('FRIK-005', 'Filetes de polloen salsa de coco', 2),
  ('FRIK-005', 'Filetes de polloen salsa de queso azul', 2),
  ('FRIK-005', 'Frikoal barril', 2),
  ('FRIK-005', 'Garbanzos con pollo Friko y vegetales', 2),
  ('FRIK-005', 'Guiso español con pollo Friko', 2),
  ('FRIK-005', 'Halloween para adultosFiletes en vino tinto', 2),
  ('FRIK-005', 'Lasañade pan', 2),
  ('FRIK-005', 'Mini chuzos con confiturade tomate de árbol', 2),
  ('FRIK-005', 'Mini chuzos de pollo a la miel', 2),
  ('FRIK-005', 'Nachoslocos', 2),
  ('FRIK-005', 'Papá en la cocinaSudado de pollo', 2),
  ('FRIK-005', 'Paqueticos de pollo thai', 2),
  ('FRIK-005', 'Pollo al curry', 2),
  ('FRIK-005', 'Pollo cremosocon alcaparras al limón', 2),
  ('FRIK-005', 'Pollo Friko asado con cerveza', 2),
  ('FRIK-005', 'Quesadilla de polloy vegetales asados', 2),
  ('FRIK-005', 'Rollo de pollo   en salsa de champiñones', 2),
  ('FRIK-005', 'Rollos de contramusloa la italiana', 3),
  ('FRIK-005', 'Súper picada navideña', 2),
  ('FRIK-006', '3 almuerzos rápidos con pechuga Friko', 3),
  ('FRIK-006', 'Aguacates rellenosde pollo y vegetales', 2),
  ('FRIK-006', 'Arroz con pollo colombiano', 2),
  ('FRIK-006', 'Berenjenas rellenasde Pollo Friko', 1),
  ('FRIK-006', 'Bowl de polloy pasta', 2),
  ('FRIK-006', 'Bowl keto con spaguettisde zucchini', 2),
  ('FRIK-006', 'Cacerola de pollo Frikocon huevo', 2),
  ('FRIK-006', 'Causa limeña con pollo Friko', 2),
  ('FRIK-006', 'Chop Suey  con Filetes de pollo Friko', 2),
  ('FRIK-006', 'Cremoso de papa y zanahoria', 2),
  ('FRIK-006', 'Croquette Normand', 2),
  ('FRIK-006', 'Crunchy wrapde pollo Friko', 2),
  ('FRIK-006', 'Delicioso curry  de pollo', 2),
  ('FRIK-006', 'Ensalada de pollo Friko  y quinua', 2),
  ('FRIK-006', 'Ensaladas de pollo para un almuerzo saludable', 2),
  ('FRIK-006', 'Ensalada especial  de wrap de lechuga', 2),
  ('FRIK-006', 'Ensalada griega con pollo', 2),
  ('FRIK-006', 'Ensalada otoñoFriko', 2),
  ('FRIK-006', 'Fajitas de pollo mexicanas', 2),
  ('FRIK-006', 'Fiambre de pollo con manzana al romero', 2),
  ('FRIK-006', 'Filete de pechuga Friko ¡como de un chef!', 3),
  ('FRIK-006', 'Filete de PechugaJardinera Friko', 3),
  ('FRIK-006', 'Filetes de pechugaapanados a la parmesana', 3),
  ('FRIK-006', 'Filetes festivos', 2),
  ('FRIK-006', 'Folding Wrap Friko', 2),
  ('FRIK-006', 'Francesa de pollo y huevo', 2),
  ('FRIK-006', 'Gratinado de polloy zucchini', 2),
  ('FRIK-006', 'Halloween para niñosCupcakes de pollo', 2),
  ('FRIK-006', 'Bowl de ensalada Intensamente', 2),
  ('FRIK-006', 'Lumpias fáciles para airfryer', 2),
  ('FRIK-006', 'Nachoslocos', 2),
  ('FRIK-006', 'Nuggets enAirfryer', 1),
  ('FRIK-006', 'Paella casera:¡fácil, rápida y deliciosa!', 2),
  ('FRIK-006', 'Paqueticos de pollo thai', 2),
  ('FRIK-006', 'Pastas, espinacas y pollo Friko', 2),
  ('FRIK-006', 'Pasta rellenade pollo', 1),
  ('FRIK-006', 'Patacones condip de pollo', 2),
  ('FRIK-006', 'Pechuga Friko  al vapor con brócoli', 3),
  ('FRIK-006', 'Pechugas de pollo marineras', 2),
  ('FRIK-006', 'Picada de pollo y vegetales', 2),
  ('FRIK-006', 'Pollo a la naranja', 2),
  ('FRIK-006', 'Pollo al curry con arroz', 2),
  ('FRIK-006', 'Pollo encostrado en pimienta', 2),
  ('FRIK-006', 'Pollo Friko apanado  en coco con salsa de maracuyá', 2),
  ('FRIK-006', 'Portobellos rellenos  Friko', 2),
  ('FRIK-006', 'Sándwich de picnic con Friko', 2),
  ('FRIK-006', 'Sándwich de tomates asados  y nuggets Friko', 2),
  ('FRIK-006', 'Sandwich parrillero ligero Friko', 1),
  ('FRIK-006', 'Súper picada navideña', 2),
  ('FRIK-006', 'Tartine de Pollo', 2),
  ('FRIK-006', 'Tostadas de Búfalo Friko', 2),
  ('FRIK-006', 'Tres arepitas con pollo Friko', 2),
  ('FRIK-006', 'Trozos de Pechuga Apanados para el Día del Niño', 3),
  ('FRIK-006', 'Trozos de pechuga endip de queso y miel picante', 3),
  ('FRIK-006', 'Trozos de pollo  en salsa de yogur', 2),
  ('FRIK-006', 'Wrap de vegetales asadosy pollo Friko', 2),
  ('FRIK-007', 'Aguacates rellenosde pollo y vegetales', 2),
  ('FRIK-007', 'Arroz con pollo colombiano', 2),
  ('FRIK-007', 'Berenjenas rellenasde Pollo Friko', 1),
  ('FRIK-007', 'Bowl keto con spaguettisde zucchini', 2),
  ('FRIK-007', 'Chop Suey  con Filetes de pollo Friko', 2),
  ('FRIK-007', 'Cremoso de papa y zanahoria', 2),
  ('FRIK-007', 'Delicioso curry  de pollo', 2),
  ('FRIK-007', 'Ensalada de pollo Friko  y quinua', 2),
  ('FRIK-007', 'Ensalada griega con pollo', 2),
  ('FRIK-007', 'Ensalada otoñoFriko', 2),
  ('FRIK-007', 'Fiambre de pollo con manzana al romero', 2),
  ('FRIK-007', 'Francesa de pollo y huevo', 2),
  ('FRIK-007', 'Lumpias fáciles para airfryer', 2),
  ('FRIK-007', 'Nuggets enAirfryer', 1),
  ('FRIK-007', 'Pasta rellenade pollo', 1),
  ('FRIK-007', 'Patacones condip de pollo', 2),
  ('FRIK-007', 'Pechuga Friko  al vapor con brócoli', 2),
  ('FRIK-007', 'Pechugas de pollo marineras', 2),
  ('FRIK-007', 'Picada de pollo y vegetales', 2),
  ('FRIK-007', 'Pollo a la naranja', 2),
  ('FRIK-007', 'Sándwich de tomates asados  y nuggets Friko', 2),
  ('FRIK-007', 'Sandwich parrillero ligero Friko', 1),
  ('FRIK-007', 'Súper picada navideña', 2),
  ('FRIK-007', 'Tartine de Pollo', 2),
  ('FRIK-007', 'Tres arepitas con pollo Friko', 2),
  ('FRIK-007', 'Trozos de Pechuga Apanados para el Día del Niño', 3),
  ('FRIK-007', 'Trozos de pechuga endip de queso y miel picante', 3),
  ('FRIK-007', 'Trozos de pollo  en salsa de yogur', 2),
  ('FRIK-007', 'Waffles de Pollo', 1),
  ('FRIK-007', 'Wrap de vegetales asadosy pollo Friko', 2),
  ('FRIK-008', 'Mini chuzos con confiturade tomate de árbol', 3),
  ('FRIK-008', 'Mini chuzos de pollo a la miel', 3),
  ('FRIK-008', 'Súper picada navideña', 2),
  ('FRIK-009', 'Nuggets enAirfryer', 3),
  ('FRIK-009', 'Sándwich de tomates asados  y nuggets Friko', 3),
  ('FRIK-009', 'Tres arepitas con pollo Friko', 1),
  ('ANTI-002', 'Pechugas de pollo marineras', 2)
) AS matches(sku, titulo, relevancia)
-- Un mismo SKU puede estar en varias regiones; DISTINCT ON evita duplicados de producto_id
JOIN (
  SELECT DISTINCT ON (sku) id, sku
  FROM public.productos
  ORDER BY sku, id
) p ON p.sku = matches.sku
JOIN public.recetas r ON trim(r.titulo) = trim(matches.titulo)
ON CONFLICT (producto_id, receta_id)
  DO UPDATE SET relevancia = EXCLUDED.relevancia;

-- ----------------------------------------------------------------
-- Verificación: debe mostrar 9 SKUs con recetas
-- ----------------------------------------------------------------
SELECT
  p.sku,
  p.nombre,
  COUNT(*)          AS total_recetas,
  MAX(pr.relevancia) AS max_relevancia
FROM public.producto_receta pr
JOIN public.productos p ON pr.producto_id = p.id
GROUP BY p.sku, p.nombre
ORDER BY total_recetas DESC;